export const GET_CAT_REQUEST = 'GET_CAT_REQUEST'
export const GET_CAT_SUCCESS = 'GET_CAT_SUCCESS'
export const GET_CAT_FAILURE = 'GET_CAT_FAILURE'

export const VOTE_CAT_REQUEST = 'VOTE_CAT_REQUEST'
export const VOTE_CAT_SUCCESS = 'VOTE_CAT_SUCCESS'
export const VOTE_CAT_FAILURE = 'VOTE_CAT_FAILURE'