export const SEARCH_GET_BREEDS_AND_CATEGORIES_REQUEST = 'SEARCH_GET_BREEDS_AND_CATEGORIES_REQUEST'
export const SEARCH_GET_BREEDS_AND_CATEGORIES_FINISHED = 'SEARCH_GET_BREEDS_AND_CATEGORIES_FINISHED'

export const SEARCH_REQUEST = 'SEARCH_REQUEST'
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS'
export const SEARCH_FAILURE = 'SEARCH_FAILURE'