export const GET_BREED_DETAILS_REQUEST = 'GET_BREED_DETAILS_REQUEST'
export const GET_BREED_DETAILS_SUCCESS = 'GET_BREED_DETAILS_SUCCESS'
export const GET_BREED_DETAILS_FAILURE = 'GET_BREED_DETAILS_FAILURE'